# Anthropic Configuration
ANTHROPIC_API_KEY = "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"

# Email Configuration
EMAIL_ADDRESS = "micheloid01@gmail.com"
EMAIL_PASSWORD = "dtpc oibx okaa ektw"

# Google Sheets Configuration
SHEET_ID = "13wpZcbAHOXVbNyvIVeWvZZDAJxxIHOrTEOPieY-ylQo"

# Service Account Details
project_id = "jensassistant"
private_key_id = "001e17f4ee10951bdbbc20adf725aa4bdd955fb4"
private_key = '''
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCoDjNwJwCoApIP
zYeaETJ+otD6HmKXkCoefKoxZ+GzhpFfvXUVjfOyOGmbUw/vaQAhRAkgItXWdfej
x4bGI6EzR2+Tj96HmEB3/cnYp6UXKzPMoRYNiQUSLW7eiOuIyxjCl5KLChDqe+ix
JGxnGtj6bKA/iGdGd5eW3pupOgqBBsEfjbP7KrLbNUQD/f8A170kN5XCO1Mc2cha
IEbxFwLmUHpf1EQMR44f7N7aT203epwgVygK91IzF/3WguNH/jt++gpV0GpEWmAN
czCGnfVjrcOyTV4zbWbEJWRqVrln2ZZpq9nxkYmvrkcyb0fQ8sHk4lVE5cPZLwt8
D0EH8/33AgMBAAECggEADAPT5qFLOTfR1IJnvvqaxxYB5df1SYu7jylvi4+3QbwN
ubAUZmGbOjMxTbMPERlLMpWoJ12GN0qA1XtG5fSXKlDhp8Wh7cTTWyDQZQZ7VaA3
mFot9vLEY4vPAOb+G+4VS5hFmF40XmdUeBG4FFkFiUXp4RDx/UZAlr88lsk5Bgdl
Uya1+EGpsws1DyEkDhaQ0I1YUKqXbJ/S9QhyooWNtw19XGQist+kSuH92imGAlIH
R/abd9VKofCwJAqj3BGbq8OY1Qctd+xzC9jsQTfuLKRr5IOQKKn0UCzROp74p9rr
8IqMJvh9CLjhK6oICmCWLvPwPEQYmhGPHo++1mqcHQKBgQDiL97fFkEBk41lOOL4
rXsSIfCJEbiXCryEHsFLVwhziW5y1M0o7V8UxMFj6Zy+sxmoPHPKUtupcyo6BaXp
x6qbqv9GFBvvwLcV12xct1UMr5D76FlwWnuzMu2FG8RB4TY22ArAFU7gse/AnmAz
gPgieD0o/HQoXQEmNUDCuTDMSwKBgQC+NNLbncTJsPIWqxPbc19Zuv7Mw5V/VJD0
hl1xnlzlYeX30HGde7eXrZncWVV9U0kgJXVN57Wuh07EkXgl6NItUQ42RskhpGWi
UuBiikvBhm5S3reZzcrGKfmlejdDYn3nXsplUAcbHZokv8HW2eb6QXLCqMAEptB7
5zopEM6xhQKBgDPNxvvNOwJDayT9zG4sPX2/rDmYh3CAkwCnkpnQyyy7E0LVnk97
XkWBctGRVccPehbgEZ0LMSg0Kj2zwXYzts2Ecob4YBWfS8+C0VzC2IXZSBmJ88IZ
1y8JwQC1hVOZYzNYc83ek3w/BKxXGa1yImKyqz9R4sDD3FmF5Nk0VQrVAoGAeOij
US/NNFjiyz4c9Vc1uZiA+DEsCzD6pDX1mJAOhVHiGdHLJ0zJvAWC1OuEyJH03hZx
pwAwIa2piJLgSVjioiPwYNhGarhSUwlT0dAPsAmAf/VLyN1klOuB4or6Lj+hwT4k
cpqYqcf7gHjVA3qotVR9Wvhid5KC3QBznD8u5PECgYEAnNu2+Oa18CP1/Ug2xXJS
eNHMpT4mkVuCiavq+5Ashfhfwu4fxhFfFR38OFIkjwljJi0WQJA/0nf7R716DILB
8+OZFpPqXcFVCePhTBG+B5uususnGO60UCKTDgvNkifYyTOf9Ot5UzlSLbREbyWE
nDT+e/fg2XZ7DRhrC65eMNI=
-----END PRIVATE KEY-----
'''
client_email = "jen03-383@jensassistant.iam.gserviceaccount.com"
client_id = "113446235113597795925"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/jen03-383%40jensassistant.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
